### ISSUE TITLE
No source distribution or Python 3 wheel on PyPI for 0.2.1

### ISSUE THREAD

**Issue by tmehlinger** [eleme/gunicorn_thrift#12]
When I try to install dependencies for an application that uses `gunicorn_thrift`, I get errors from pip complaining about not finding a version that satisfies my given requirement.

Looking on PyPI, the only available distribution for `gunicorn_thrift` 0.2.1 is a Python 2 wheel.

Can you guys please upload an sdist and a Python 3 wheel?

Thanks!

**Comment by wooparadog** [comment]
I've just uploaded a sdist and wheel version. Sorry for the inconvenience..

**Comment by tmehlinger** [comment]
No worries, thanks very much. :smiley:
