### ISSUE TITLE
请问是否支持TMultiplexedProcessor？

### ISSUE THREAD

**Issue by caiqingmao** [eleme/gunicorn_thrift#17]
写了一个thrift文件 
service PingPong {
    string ping()
}
service Hello{
    string hello2015()
}

然后使用thriftpy

import thriftpy
from thriftpy.thrift import TProcessor
from thriftpy.thrift import TMultiplexedProcessor

class PingPongDispatcher(object):
    def ping(self):
        return "pong"

class HelloDispatcher(object):
    def hello2015(self):
        return "hello2015"

pingpong_thrift = thriftpy.load("pingpong.thrift")
app1 = TProcessor(pingpong_thrift.PingPong, PingPongDispatcher())
app2 = TProcessor(pingpong_thrift.Hello, HelloDispatcher())
processor = TMultiplexedProcessor()
processor.register_processor("pingpong", app1)
processor.register_processor("hello", app2)

然后使用gunicorn_thrift启动
gunicorn_thrift app:processor -k thrift_gevent --thrift-protocol-factory thriftpy.protocol:TBinaryProtocolFactory --thrift-transport-factory thriftpy.transport:TBufferedTransportFactory --error-log -

客户端使用的是java、访问python服务器端时出现错误

[2015-08-29 14:09:49 +0800] [719] [ERROR] 'TCyBufferedTransportFactory' object has no attribute 'getTransport'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gunicorn_thrift/gevent_worker.py", line 42, in handle
    self.get_thrift_transports_and_protos(result)
  File "/Library/Python/2.7/site-packages/gunicorn_thrift/gevent_worker.py", line 25, in get_thrift_transports_and_protos
    itrans = self.app.tfactory.getTransport(result)
AttributeError: 'TCyBufferedTransportFactory' object has no attribute 'getTransport'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/gunicorn_thrift/gevent_worker.py", line 59, in handle
    itrans.close()
UnboundLocalError: local variable 'itrans' referenced before assignment
<Greenlet at 0x104e74870: <functools.partial object at 0x104ea4ec0>(<socket at 0x104f24750 fileno=11 sock=127.0.0.1:80, ('127.0.0.1', 49831))> failed with UnboundLocalError

请问这是怎么回事？本人新手学习thriftpy和使用gunicorn_thrift、跪请大神回复

**Comment by wooparadog** [comment]
Hi, there're 2 problems with your setup.

1. gunicorn_thrift should be started with 

    ```bash
gunicorn_thrift app:processor -k thriftpy_gevent --thrift-protocol-factory thriftpy.protocol:TBinaryProtocolFactory --thrift-transport-factory thriftpy.transport:TBufferedTransportFactory --error-log - 
    ```
    please notice `-k thriftpy_gevent` rather than `-k thrift_gevent`

2. service name not the same with thrift file. This might not be a problem, but out of some concerns, you should keep them the same.

    ```
    processor.register_processor("PingPong", app1)
    processor.register_processor("Hello", app2)
    ```

    ```

**Comment by caiqingmao** [comment]
我使用了thriftpy_gevent代替了thrift_gevent,解决了上述的问题，但是当客户端和服务器端通信时，服务器端能返回正确的数据，但是也会出现异常，如下：
 ```     
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/gunicorn_thrift/thriftpy_gevent_worker.py", line 88, in handle
    itrans.close()
  File "thriftpy/transport/buffered/cybuffered.pyx", line 38, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.close (thriftpy/transport/buffered/cybuffered.c:1358)
  File "/Library/Python/2.7/site-packages/thriftpy/transport/socket.py", line 29, in close
    self.handle.shutdown(socket.SHUT_RDWR)
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 517, in shutdown
    self._sock.shutdown(how)
error: [Errno 57] Socket is not connected
<Greenlet at 0x107703730: <functools.partial object at 0x107780f70>(<socket at 0x1077b03d0 fileno=11 sock=127.0.0.1:80, ('127.0.0.1', 49525))> failed with error
```

客户端使用的是java，代码如下：


``` 
public static void main(String[] args) {
        try {
            TTransport tTransport = new TSocket("127.0.0.1", 8000);
            tTransport.open();
            TProtocol protocol = new TBinaryProtocol(tTransport);
            TMultiplexedProtocol hello = new TMultiplexedProtocol(protocol, "hello");
            Hello.Client client = new Hello.Client(hello);
            String response = client.hello2015();
            System.out.println(response);
            tTransport.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```


能否帮忙分析一下哪里的代码出现了问题

启动方式
`gunicorn_thrift app:processor -k thriftpy_gevent --thrift-protocol-factory thriftpy.protocol:TBinaryProtocolFactory --thrift-transport-factory thriftpy.transport:TBufferedTransportFactory --error-log -`

**Comment by wooparadog** [comment]
尝试升级一下 thriftpy 的版本吧. 

https://github.com/eleme/thriftpy/commit/40f97ec97b8fd0147332427a31317b20c24c99e2

**Comment by caiqingmao** [comment]
解决了，谢谢。
