### ISSUE TITLE
New Relic Agent / Monitoring

### ISSUE THREAD

**Issue by CodyMorris** [eleme/gunicorn_thrift#19]
Hey Eleme.

For a few days I've been trying to use New Relic monitoring on my gunicorn_thrift app.  I've had no issues with my traditional gunicorn apps.  I can launch my gunicorn_thrift application with no issues, but new relic gets no data.

I can launch it with Gunicorn like so:
```
NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program [gunicorn commands here]
```
But if I use:
```
NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn_thrift tests.thriftpy_app:app -k thriftpy_sync \
  --thrift-protocol-factory \
    thriftpy.protocol:TCyBinaryProtocolFactory \
  --thrift-transport-factory \
    thriftpy.transport:TCyBufferedTransportFactory

```

I get no errors, but no communication to new relic.

https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-admin-script

Any advice for me?

**Comment by wooparadog** [comment]
Hi, I'm not so familiar with new relic. But are you using it to track rps(the stuff that gunicorn does) or app wise performance(like mysql query time)? 

If you are using it to monitor rps, I don't think new relic supports gunicorn-thrift. But if you are using it to track app performance, there shouldn't be any problem. Did you install new relic in the same virtualenv as gunicorn_thrift maybe?

**Comment by CodyMorris** [comment]
Thanks for the response!

New Relic tracks app performance, so I think it should definitely be possible.  New Relic and gunicorn_thrift are both in the same virtualenv, and if I run my application I can see new relic reporting logs.  Unfortunately thats not making its way back to New Relic.

I'll keep troubleshooting it, thanks for the assistance if you have any ideas!
