### ISSUE TITLE
有个疑问?

### ISSUE THREAD

**Issue by rfyiamcool** [eleme/gunicorn_thrift#32]
Thrift server 本身不就有多进程模型吧 ，你让gunicorn 兼容thrift的协议是为了使用gunicorn的进程管理模型么？   好奇...

**Comment by wooparadog** [comment]
Thriftpy 并没有多进程的 server，同时 gunicorn 的进程管理的确非常有用。

**Comment by wooparadog** [comment]
Close old issues, feel free to reopen anytime.
