### ISSUE TITLE
Is it right always log a full stack exception?

### ISSUE THREAD

**Issue by h3l** [eleme/gunicorn_thrift#46]
In my situation, I just set client timeout as low as possible described in https://github.com/eleme/gunicorn_thrift/issues/45, but i always got a timeout message like https://github.com/eleme/thrift_connector/issues/48 said.

At last, I found that in https://github.com/eleme/gunicorn_thrift/blob/master/gunicorn_thrift/thriftpy_sync_worker.py#L75, it always log exception with full error stack.

But I think we should first identify to exception like below:

```
if isinstance(e, socket.timeout):
    self.log.info("timeout")
else:
    self.log.exception(e)
```

**Comment by wooparadog** [comment]
It's not...

We changed this behavior in gevent worker(https://github.com/eleme/gunicorn_thrift/blob/master/gunicorn_thrift/thriftpy_gevent_worker.py#L178)

Fix is underway

**Comment by wooparadog** [comment]
You can install the newest version from github, I'll wait a bit longer to do a version bump.

**Comment by h3l** [comment]
Finaly , I chosen gevent work. -0-
