### ISSUE TITLE
Problem about running gunicorn_thrift

### ISSUE THREAD

**Issue by preytaren** [eleme/gunicorn_thrift#51]
I'v installed gunicorn_thrift， but can't find the command gunicorn_thrift？

**Comment by aawilson** [comment]
This needs a lot more information before anyone can be helpful. How did you install it? What platform? Did you install it globally, or in a virtualenv? What version of Python?

**Comment by wooparadog** [comment]
@preytaren  this issue is more related to your python setup rather than gunicorn_thrift itself. 

Please create a new virtualenv and install gunicorn_thrift in it to check if it's gunicorn_thrift's problem, meanwhile I'll close this issue.  Feel free to reopen it.

**Comment by zifenghuang1** [comment]
I met the same issue.

After cloning repo, i just run "python setup.py install" in a virtualenv. It's werid that log does not show gunicorn_thrift script was installed.

`
(.venv) ➜  gunicorn_thrift git:(master) ✗ python setup.py install
running install
running bdist_egg
running egg_info
creating gunicorn_thrift.egg-info
writing requirements to gunicorn_thrift.egg-info/requires.txt
writing gunicorn_thrift.egg-info/PKG-INFO
writing top-level names to gunicorn_thrift.egg-info/top_level.txt
writing dependency_links to gunicorn_thrift.egg-info/dependency_links.txt
writing entry points to gunicorn_thrift.egg-info/entry_points.txt
writing manifest file 'gunicorn_thrift.egg-info/SOURCES.txt'
reading manifest file 'gunicorn_thrift.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '.*.swp' found under directory '.'
warning: no previously-included files matching '.*.swo' found under directory '.'
warning: no previously-included files matching '*' found under directory 'venv'
warning: no previously-included files matching '*' found under directory 'dist'
warning: no previously-included files matching '*' found under directory 'build'
writing manifest file 'gunicorn_thrift.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gunicorn_thrift
copying gunicorn_thrift/__init__.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/config.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/gevent_worker.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/six.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/sync_worker.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/thriftapp.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/thriftpy_gevent_worker.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/thriftpy_sync_worker.py -> build/lib/gunicorn_thrift
copying gunicorn_thrift/utils.py -> build/lib/gunicorn_thrift
creating build/bdist.macosx-10.12-x86_64
creating build/bdist.macosx-10.12-x86_64/egg
creating build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/__init__.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/config.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/gevent_worker.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/six.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/sync_worker.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/thriftapp.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/thriftpy_gevent_worker.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/thriftpy_sync_worker.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
copying build/lib/gunicorn_thrift/utils.py -> build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/config.py to config.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/gevent_worker.py to gevent_worker.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/six.py to six.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/sync_worker.py to sync_worker.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/thriftapp.py to thriftapp.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/thriftpy_gevent_worker.py to thriftpy_gevent_worker.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/thriftpy_sync_worker.py to thriftpy_sync_worker.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/gunicorn_thrift/utils.py to utils.pyc
creating build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
creating dist
creating 'dist/gunicorn_thrift-0.2.21-py2.7.egg' and adding 'build/bdist.macosx-10.12-x86_64/egg' to it
removing 'build/bdist.macosx-10.12-x86_64/egg' (and everything under it)
Processing gunicorn_thrift-0.2.21-py2.7.egg
creating /Users/zifeng.huang/Desktop/study/test/gunicorn_thrift/.venv/lib/python2.7/site-packages/gunicorn_thrift-0.2.21-py2.7.egg
Extracting gunicorn_thrift-0.2.21-py2.7.egg to /Users/zifeng.huang/Desktop/study/test/gunicorn_thrift/.venv/lib/python2.7/site-packages
Adding gunicorn-thrift 0.2.21 to easy-install.pth file

Installed /Users/zifeng.huang/Desktop/study/test/gunicorn_thrift/.venv/lib/python2.7/site-packages/gunicorn_thrift-0.2.21-py2.7.egg
Processing dependencies for gunicorn-thrift==0.2.21
Finished processing dependencies for gunicorn-thrift==0.2.21
`
My platform is Darwin appledeMacBook-Pro-2.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64.

But if i use "python setup.py develop", the gunicorn_thrift script will be installed.
