### ISSUE TITLE
Update pypi distribution

### ISSUE THREAD

**Issue by ar090** [eleme/gunicorn_thrift#56]
I noticed installing from pypi and using a thriftpy_gevent worker is broken in the latest version 0.2.21. 

![image](https://user-images.githubusercontent.com/17073553/44753299-73f39f00-aad2-11e8-8efb-d13231e206d7.png)

Installing directly from this repo seems to solve the problem:
`git+https://github.com/eleme/gunicorn_thrift.git`

After further inspection the code looks pretty different on pypi
pypi 0.2.21
`thriftpy_gevent_worker.py` line 100
![image](https://user-images.githubusercontent.com/17073553/44753198-2119e780-aad2-11e8-9bf0-f9e57daefe71.png)

this repo:
![image](https://user-images.githubusercontent.com/17073553/44753261-4e669580-aad2-11e8-9854-635ee788ae51.png)

Any chance of updating pypi distribution?

Thanks!

**Comment by wooparadog** [comment]
Yeah, I'll publish 0.2.22 today. But because I lost control of this repo, I'll maintain it in my fork.

**Comment by ar090** [comment]
Just bumped to `0.2.22` and it looks good. Thank you!
