### ISSUE TITLE
没有及时回收socket

### ISSUE THREAD

**Issue by vhysug** [eleme/gunicorn_thrift#73]
thriftpy2, 在client退出后，服务端检查还有这个连接的socket在ESTABLISHED状态。这个有什么方法可以主动关闭么？
目前使用了thrift_client_timeout， 但是依然不理想

**Comment by ethe** [comment]
I think it might be impossible, OS would move the socket from ESTABLISHED to CLOSE_WAIT when TCP connection is closed by remote. It is a behavior of OS rather than users.

**Comment by vhysug** [comment]
what if a tcp proxy before the sever? it's same as with none proxy?

**Comment by ethe** [comment]
It depends on your proxy, I have no idea.

**Comment by vhysug** [comment]
ok. thanks anyway.
