### ISSUE TITLE
[gunicorn compatibility issue] ImportError: cannot import name 'six' from 'gunicorn'

### ISSUE THREAD

**Issue by Sherler** [eleme/gunicorn_thrift#74]
Throw import error when using high version gunicorn as gunicorn has already remove six from it's package, in gunicorn>=20.0。[Remove six dependency](https://github.com/benoitc/gunicorn/pull/2083)。 hoping gunicorn_thrift can catch up with the new version, Thank you

**Comment by ethe** [comment]
Thank you, it will be fixed later.

**Comment by Sherler** [comment]
Still nothing happened....
